name: PostCherryPick
on:
  pull_request_target:
    types:
    - closed
    branches:
    - '202???'
    - 201911
    - 201811

jobs:
  post_cherry_pick:
    if: github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.name, 'automerge')
    runs-on: ubuntu-latest
    steps:
    - name: Debug
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo $GITHUB_CONTEXT | jq
    - name: Checkout
      uses: actions/checkout@v3
      with:
        persist-credentials: false
    - name: Main
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
        TOKEN: ${{ secrets.TOKEN }}
      run: |
        set -e
        pr_url=$(echo $GITHUB_CONTEXT | jq -r ".event.pull_request._links.html.href")
        base_ref=$(echo $GITHUB_CONTEXT | jq -r ".base_ref")
        echo ${TOKEN} | gh auth login --with-token
        comment=$(gh pr view $pr_url --json comments | jq -r '.comments | [.[] | select(.author.login=="mssonicbld")] | first | .body')
        origin_pr_url=$(echo $comment | sed 's/Original PR: //')
        echo =============================
        echo pr_url:        $pr_url
        echo base_ref:      $base_ref
        echo comment:       $comment
        echo origin_pr_url: $origin_pr_url
        echo =============================
        # Add label
        if [[ "$origin_pr_url" == "" ]];then
          echo No comment from mssonicbld
          exit 0
        fi
        gh pr edit $origin_pr_url --add-label "Included in ${base_ref} Branch"
        gh pr edit $origin_pr_url --remove-label "Created PR to ${base_ref} Branch"
